#!/bin/bash

ROOT=""
set +f

# Simple Shell Cron for systems without cron
#shellcheck disable=SC2086 
#shellcheck disable=SC1091
source $ROOT/usr/lib/pcron/func.sh

# Threads 1+: Listen for pcrontab changes and regenerate scripts
parse_pcrontab() {
    input_file="$1"
    username="$2"
    # Validate username using id -u
    if ! id -u "$username" >/dev/null 2>&1; then
        log "parser" "User $username does not exist"
        exit 1
    fi
    
    # Clean old scripts
    find "$ROOT/var/lib/pcron/scripts//" -name "pcron_${username}_*" -delete
    while true; do
        # Check if file exists
        if [ ! -f "$input_file" ]; then
            log "parser" "File $input_file does not exist"
            # Clean old scripts
            find "$ROOT/var/lib/pcron/scripts/" -name "pcron_${username}_*" -delete
            exit 1
        fi
        pcrontab_env=()
        pcrontab_env_count=0
        pcron_script_count=0
        # Parse input file and generate scripts for each entry
        while IFS= read -r entry; do
            # Ignore comments and empty lines
            if [[ $entry == \#* ]] || [ -z "$entry" ]; then
                continue
            fi
            log "parser" "Parsing entry: $entry"
            # If line starts with capital letter, assume it's a environment variable and add it to the generated script
            if [[ $entry == [A-Z]* ]]; then
                pcrontab_env[pcrontab_env_count]="$entry"
                pcrontab_env_count=$((pcrontab_env_count + 1))
                log "parser" "Added environment variable: $entry"
                continue
            fi
            # Extract fields from entry
            seconds=$(echo "$entry" | awk '{print $1}')
            minute=$(echo "$entry" | awk '{print $2}')
            hour=$(echo "$entry" | awk '{print $3}')
            day=$(echo "$entry" | awk '{print $4}')
            month=$(echo "$entry" | awk '{print $5}')
            weekday=$(echo "$entry" | awk '{print $6}')
            command=$(echo "$entry" | cut -d' ' -f7-)

            # Parse and verify time
            if [ -z "$seconds" ] || [ -z "$minute" ] || [ -z "$hour" ] || [ -z "$day" ] || [ -z "$month" ] || [ -z "$weekday" ] || [ -z "$command" ]; then
                # Invalid entry
                log "parser" "Invalid entry: $entry"
                continue
            fi
            # Parse seconds
            retval=$("$ROOT/usr/lib/pcron/parse-time.sh" "$seconds" 3)
            if [ "$retval" == "E" ]; then
                # Invalid entry
                log "parser" "Invalid entry: $entry"
                continue
            elif [ -z "$retval" ]; then
                # Empty time array
                seconds_arr=()
            else
                seconds_arr=("$retval")
            fi

            # Parse minutes
            retval=$("$ROOT/usr/lib/pcron/parse-time.sh" "$minute" 59)
            if [ "$retval" == "E" ]; then
                # Invalid entry
                log "parser" "Invalid entry: $entry"
                continue
            elif [ -z "$retval" ]; then
                # Empty time array
                minutes_arr=()
            else
                minutes_arr=("$retval")
            fi

            # Parse hours
            retval=$("$ROOT/usr/lib/pcron/parse-time.sh" "$hour" 23)
            if [ "$retval" == "E" ]; then
                # Invalid entry
                log "parser" "Invalid entry: $entry"
                continue
            elif [ -z "$retval" ]; then
                # Empty time array
                hours_arr=()
            else
                hours_arr=("$retval")
            fi

            # Parse days
            retval=$("$ROOT/usr/lib/pcron/parse-time.sh" "$day" 31)
            if [ "$retval" == "E" ]; then
                # Invalid entry
                log "parser" "Invalid entry: $entry"
                continue
            elif [ -z "$retval" ]; then
                # Empty time array
                days_arr=()
            else
                days_arr=("$retval")
            fi

            # Parse months
            retval=$("$ROOT/usr/lib/pcron/parse-time.sh" "$month" 12)
            if [ "$retval" == "E" ]; then
                # Invalid entry
                log "parser" "Invalid entry: $entry"
                continue
            elif [ -z "$retval" ]; then
                # Empty time array
                months_arr=()
            else
                months_arr=("$retval")
            fi

            # Parse weekdays
            retval=$("$ROOT/usr/lib/pcron/parse-time.sh" "$weekday" 6)
            if [ "${retval:0:1}" == "E" ]; then
                # Invalid entry
                log "parser" "Invalid entry: $entry"
                continue
            elif [ -z "$retval" ]; then
                # Empty time array
                weekdays_arr=()
            else
                weekdays_arr=("$retval")
            fi

            # Generate script for entry
            script_name=$ROOT/var/lib/pcron/scripts//"pcron_${username}_${pcron_script_count}"
            # Script header
            cat > "$script_name" <<EOF
#!/bin/bash
# Auto generated by pcrontab, DO NOT EDIT
source $ROOT/usr/lib/pcron/func.sh
pidfile="${script_name}.pid"
EOF
            # Environment variables
            for (( i = 0; i < "${#pcrontab_env[@]}"; i++ )); do
                echo "export ${pcrontab_env[i]}" >> "$script_name"
            done
            # Time and command
            if [ "$username" == "root" ]; then
                echo "command='$command'" >> "$script_name"
            else
                echo "command='sudo -u $username $command'" >> "$script_name"
            fi
            if [[ -v days_arr[@] && ${#days_arr[@]} -gt 0 ]]; then
                echo "days=(" "${days_arr[@]}" ")" >> "$script_name"
            fi
            if [[ -v months_arr[@] && ${#months_arr[@]} -gt 0 ]]; then
                echo "months=(" "${months_arr[@]}" ")" >> "$script_name"
            fi
            if [[ -v weekdays_arr[@] && ${#weekdays_arr[@]} -gt 0 ]]; then
                echo "weekdays=(" "${weekdays_arr[@]}" ")" >> "$script_name"
            fi
            if [[ -v hours_arr[@] && ${#hours_arr[@]} -gt 0 ]];then
                echo "hours=(" "${hours_arr[@]}" ")" >> "$script_name"
            fi
            if [[ -v minutes_arr[@] && ${#minutes_arr[@]} -gt 0 ]]; then
                echo "minutes=(" "${minutes_arr[@]}" ")" >> "$script_name"
            fi
            if [[ -v seconds_arr[@] && ${#seconds_arr[@]} -gt 0 ]]; then
                echo "seconds=(" "${seconds_arr[@]}" ")" >> "$script_name"
            fi
            # Script footer
            cat >> "$script_name" <<EOF
verifyTime
checkPID
# Run command
log "runner" "Running command: '\$command'"
eval "\$command"
EOF
            chmod +x "$script_name"
            log "parser" "Generated script for $username: $script_name"

            pcron_script_count=$((pcron_script_count+1))
        done < "$input_file"


        # Monitor input file for changes
        inotifywait -q -e modify "$input_file"
        log "parser" "Re-parsing $input_file file"
        
    done
}

# Thread 2: Create threads to run parsers
# File to parse: 
# 1. /etc/pcrontab - root
# 2. /etc/pcron/pcrontab<username> - user
run_parsers() {
    parse_pcrontab "$ROOT/etc/pcrontab" root &
    while IFS= read -r -d '' filename; do
        _basename=$(basename "$filename")
        parse_pcrontab "$filename" "${_basename:8}" &
    done < <(find "$ROOT/etc/pcron/" -name "pcrontab*" -print0)

    while true; do
        newfile=$(inotifywait -e create -q "$ROOT/etc/pcron/" | awk '{print $1$3}')
        if test -n "$newfile"; then
            log "parser" "New file detected: $newfile"
            # Check if it's a user file (pcrontab<username>)
            if [[ $newfile == "$ROOT/etc/pcron/pcrontab"* ]]; then
                _basename=$(basename "$newfile")
                parse_pcrontab "$newfile" "${_basename:8}" &
            else
                log "parser" "Invalid file: $newfile"
            fi
        fi
    done
}
run_parsers&

# Thread 3: Run scripts

run_scripts() {
    # Wait for parsers to remove old scripts
    sleep 1
    while true; do
        run-parts --new-session "$ROOT/var/lib/pcron/scripts/" --arg="$(date +"%-S %-M %-H %-d %-m %-w")"&
        sleep 1
    done
}
run_scripts
