#!/bin/bash

# Simple Shell Cron for systems without cron
set -f
logfile="$ROOT/var/log/pcron.log"

warn() {
    echo "$@" >&2
}

pcrontab_env=()
pcrontab_env_count=0
pcron_script_count=0
# Parse /etc/pcron/pcrontab file and generate scripts for each entry
while IFS= read -r entry; do
    echo "Parsing entry: $entry" >> "$logfile"
    # Ignore comments and empty lines
    if [[ $entry == \#* ]] || [ -z "$entry" ]; then
        continue
    fi

    # If line starts with capital letter, assume it's a environment variable and add it to the generated script
    if [[ $entry == [A-Z]* ]]; then
        pcrontab_env[pcrontab_env_count]="$entry"
        pcrontab_env_count=$((pcrontab_env_count + 1))
        echo "Added environment variable: $entry" >> "$logfile"
        continue
    fi

    # Extract fields from entry
    seconds=$(echo "$entry" | awk '{print $1}')
    minute=$(echo "$entry" | awk '{print $2}')
    hour=$(echo "$entry" | awk '{print $3}')
    day=$(echo "$entry" | awk '{print $4}')
    month=$(echo "$entry" | awk '{print $5}')
    weekday=$(echo "$entry" | awk '{print $6}')
    command=$(echo "$entry" | cut -d' ' -f7-)

    # Parse and verify time
    if [ -z "$seconds" ] || [ -z "$minute" ] || [ -z "$hour" ] || [ -z "$day" ] || [ -z "$month" ] || [ -z "$weekday" ] || [ -z "$command" ]; then
        # Invalid entry
        warn "Invalid entry: $entry"
        continue
    fi
    # Parse seconds
    retval=$($ROOT/etc/pcron/parse-time.sh "$seconds" 3)
    if [ "$retval" == "E" ]; then
        # Invalid entry
        warn "Invalid entry: $entry"
        continue
    elif [ -z "$retval" ]; then
        # Empty time array
        seconds_arr=()
    else
        seconds_arr=("$retval")
    fi

    # Parse minutes
    retval=$($ROOT/etc/pcron/parse-time.sh "$minute" 59)
    if [ "$retval" == "E" ]; then
        # Invalid entry
        warn "Invalid entry: $entry"
        continue
    elif [ -z "$retval" ]; then
        # Empty time array
        minutes_arr=()
    else
        minutes_arr=("$retval")
    fi

    # Parse hours
    retval=$($ROOT/etc/pcron/parse-time.sh "$hour" 23)
    if [ "$retval" == "E" ]; then
        # Invalid entry
        warn "Invalid entry: $entry"
        continue
    elif [ -z "$retval" ]; then
        # Empty time array
        hours_arr=()
    else
        hours_arr=("$retval")
    fi

    # Parse days
    retval=$($ROOT/etc/pcron/parse-time.sh "$day" 31)
    if [ "$retval" == "E" ]; then
        # Invalid entry
        warn "Invalid entry: $entry"
        continue
    elif [ -z "$retval" ]; then
        # Empty time array
        days_arr=()
    else
        days_arr=("$retval")
    fi

    # Parse months
    retval=$($ROOT/etc/pcron/parse-time.sh "$month" 12)
    if [ "$retval" == "E" ]; then
        # Invalid entry
        warn "Invalid entry: $entry"
        continue
    elif [ -z "$retval" ]; then
        # Empty time array
        months_arr=()
    else
        months_arr=("$retval")
    fi

    # Parse weekdays
    retval=$($ROOT/etc/pcron/parse-time.sh "$weekday" 6)
    if [ "${retval:0:1}" == "E" ]; then
        # Invalid entry
        warn "Invalid entry: $entry"
        continue
    elif [ -z "$retval" ]; then
        # Empty time array
        weekdays_arr=()
    else
        weekdays_arr=("$retval")
    fi

    # Generate script for entry
    script_name=$ROOT/etc/pcron/scripts/"pcron_script_${pcron_script_count}"
    # Script header
    cat > $script_name <<EOF
#!/bin/bash
# Auto generated by pcrontab, DO NOT EDIT

EOF
    # Environment variables
    for (( i = 0; i < "${#pcrontab_env[@]}"; i++ )); do
        echo "export ${pcrontab_env[i]}" >> $script_name
    done
    echo "logfile=$logfile" >> $script_name
    # Time and command
    echo "command='$command'" >> $script_name
    if [ -n "$days_arr" ]; then
        echo "days=(" "${days_arr[@]}" ")" >> $script_name
    fi
    if [ -n "$months_arr" ]; then
        echo "months=(" "${months_arr[@]}" ")" >> $script_name
    fi
    if [ -n "$weekdays_arr" ]; then
        echo "weekdays=(" "${weekdays_arr[@]}" ")" >> $script_name
    fi
    if [ -n "$hours_arr" ]; then
        echo "hours=(" "${hours_arr[@]}" ")" >> $script_name
    fi
    if [ -n "$minutes_arr" ]; then
        echo "minutes=(" "${minutes_arr[@]}" ")" >> $script_name
    fi
    if [ -n "$seconds_arr" ]; then
        echo "seconds=(" "${seconds_arr[@]}" ")" >> $script_name
    fi
    # Script footer
    cat $ROOT/etc/pcron/pcron-scripts-template.sh >> $script_name
    chmod +x $script_name
    pcron_script_count=$((pcron_script_count+1))
    echo "Script generated: $script_name"
done < $ROOT/etc/pcron/pcrontab
